services:
  postgres:
    image: postgres:16
    container_name: home_challenge_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CTfr9619
      POSTGRES_DB: home_challenge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:16
    container_name: home_challenge_db_test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CTfr9619
      POSTGRES_DB: home_challenge_test
    ports:
      - "5433:5432"

volumes:
  postgres_data: